// <auto-generated />
namespace AuthenticatedRobot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AlgorithmUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlgorithmUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201411170119092_Algorithm-User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
